# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

author:
  name: Linh Pham
  email: hello@linh.social
title: "Linh Pham | Blog"
description: >- # this means to ignore newlines until "baseurl:"
  Writings and musings about technology, programming, and other random topics.
baseurl: "" # the subpath of your site, e.g. /blog
domain: blog.linh.social
url: "https://blog.linh.social" # the base hostname & protocol for your site, e.g. http://example.com

favicon: "/assets/images/favicon.png"
favicon_svg: "/assets/images/favicon.svg"
apple_touch_icon: "/assets/images/apple-touch-icon.png"

google_analytics: "G-9ZSYX22V2Z"

show_excerpts: true
permalink: pretty
future: false

include: [".well-known"]

# Build settings
remote_theme: questionlp/minima-plex
minima-plex:
  skin: auto
  date_format: "%d %B %Y"

  social_links:
    - { platform: mastodon, user_url: "https://linh.social/@qlp" }
    - { platform: github, user_url: "https://github.com/questionlp" }
    - { platform: flickr, user_url: "https://flickr.com/questionlp" }
    - { platform: instagram, user_url: "https://instagram.com/theqlp" }
    - { platform: donate, user_url: "https://ko-fi.com/questionlp" }
    - { platform: rss, user_url: "/feed.xml" }

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


