author:
  name: Linh Pham
  email: hello@linh.social
  pronouns: he/him/they/them
title: "Linh Pham | Blog"
description: >- # this means to ignore newlines until "baseurl:"
  Writings and musings about technology, programming, and other random topics.
baseurl: "" # the subpath of your site, e.g. /blog
domain: blog.linh.social
url: "https://blog.linh.social"
#copyright: Copyright &copy; 2023&ndash;2024 Linh Pham. All Rights Reserved.

favicon: "/assets/images/favicon.png"
favicon_svg: "/assets/images/favicon.svg"
apple_touch_icon: "/assets/images/apple-touch-icon.png"

#google_analytics: "G-9ZSYX22V2Z"

umami_analytics:
  url: "https://unagi.linhpham.org/script.js"
  data_website_id: "a12d4902-6bc1-4ef4-a33a-fccda44215bb"
  data_domains: "linh.social,blog.linh.social"

show_excerpts: true
permalink: pretty
future: true
paginate: 10
paginate_path: /blog/page:num

include: [".well-known"]

# Build settings
theme: termina-plex
termina-plex:
  date_format: "%d %B %Y"
  username: blog
  hostname: linh.social
  centered_tables: true
  standard_titles: true

  header_links:
    - { name: "About", url: "/about" }
    - { name: "Blog", url: "/blog" }
    - { name: "Links", url: "/links" }
    - { name: "Projects", url: "/projects" }

  social_links:
    - { name: "Blog", url: "/blog" }
    - { name: "Mastodon", url: "https://linh.social/@qlp", rel: "me" }
    - { name: "GitHub", url: "https://github.com/questionlp" }
    - { name: "Flickr", url: "https://flickr.com/questionlp" }
    - { name: "Instagram", url: "https://instagram.com/theqlp" }
    - { name: "Bluesky", url: "https://bsky.app/profile/linh.social" }
    - { name: "RSS", url: "/feed.xml" }

  fediverse_creator: "@qlp@linh.social"

  # social_links:
  #   - { platform: mastodon, user_url: "https://linh.social/@qlp", title: "Mastodon" }
  #   - { platform: github, user_url: "https://github.com/questionlp", title: "GitHub" }
  #   - { platform: flickr, user_url: "https://flickr.com/questionlp", title: "Flickr" }
  #   - { platform: instagram, user_url: "https://instagram.com/theqlp", title: "Instagram" }
  #   - { platform: bluesky, user_url: "https://bsky.app/profile/linh.social", title: "Bluesky"}
  #   - { platform: patreon, user_url: "https://patreon.com/Linh_Pham", title: "Patreon"}
  #   - { platform: rss, user_url: "/feed.xml", title: "RSS Feed" }

kramdown:
  smart_quotes: apos,apos,quot,quot

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh
